#!/usr/bin/env python

from sentence import Sentence
from analysis import Ranking
import sys


if len(sys.argv) <= 1 :
    print "Please supply file apt description input"
    exit()

searchTerms = raw_input("search :  ")
search = Sentence(searchTerms)

print searchTerms

# for each input file, do analysis
for i in range(1, len(sys.argv)) :

    
    descFile = open(sys.argv[i])

    print sys.argv[i], " : "
    for desc in descFile.readlines() :
    	s = Sentence(desc)
        s.categorizeText()
        s.sentenceSplit()

        for set in sentences :
            print set

