#!/usr/bin/env python

from analysis import *
import sys


if len(sys.argv) <= 1 :
    print "Please supply file apt description input"
    exit()

searchTerms = raw_input("search :  ")

# for each input file, do analysis
for i in range(1, len(sys.argv)) :
    
    descFile = open(sys.argv[i])

    for desc in descFile.readlines() :
        generate_snippet(desc, searchTerms)

